### ISSUE TITLE
Duplicate menu for Users

### ISSUE THREAD

**Issue by howdu** [awcodes/filament-sentry#6]
After the User Resource is coppied to local app for some custom changes, it results in duplicate menu item. 

Are there any extra steps?

<img width="371" alt="Screenshot 2022-10-12 at 07 49 26" src="https://user-images.githubusercontent.com/533658/195270235-6bff02c9-83aa-4063-acf1-17106575529a.png">

**Comment by awcodes** [comment]
This may be a bug with the auto discovery in Filament I'll look into it.

Make sure to change the resource in the config file too. 

If it's still an issue you can move the User Resources out of the Filament directory to keep them from getting auto discovered since the plugin will register it based on your config setting.

**Comment by awcodes** [comment]
Sorry, i'm not able to replicate this on the latest version.

There is an artisan command you can run to eject the resources into your app that will handle everything need to achieve this.

```bash
php artisan sentry:eject-resources
```
